# syntax=docker/dockerfile:latest
# FROM osrf/ros:humble-desktop-full
# torch contains ROS 2, NVIDIA CUDA, NVIDIA TensorRT, PyTorch
FROM rwthika/ros2-torch:kilted-desktop-full-torch2.5.0


MAINTAINER Jesse Morris "jesse.morris@sydney.edu.au"


# To avoid tzdata asking for geographic location...
ENV DEBIAN_FRONTEND=noninteractive

#Install build dependencies
RUN apt-get update && apt-get upgrade -y --no-install-recommends apt-utils
RUN apt-get update && apt-get install -y git cmake build-essential pkg-config
# Install xvfb to provide a display to container for GUI realted testing.
RUN apt-get update && apt-get install -y xvfb



RUN apt-get update \
    && apt-get install -y \
    python3-pip \
    openssh-client \
    software-properties-common \
    nano \
    vim \
    gedit \
    clang-format \
    && pip3 install black pre-commit \
    && rm -rf /var/lib/apt/lists/*

# ROS installs
RUN apt-get update && apt-get install -y \
      ros-kilted-ros2cli-common-extensions \
      ros-kilted-vision-opencv \
      nlohmann-json3-dev

# other deps
RUN apt-get install libpng++-dev

RUN python3 -m pip install pylatex evo setuptools pre-commit scipy argcomplete black pre-commit

# Install dependencies
RUN pip3 install PyQt6

RUN apt-get update && apt-get install -y \
    libxcb-cursor0 \
    libxkbcommon-x11-0 \
    libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
    libxcb-render-util0 libxcb-shape0 libxcb-xinerama0 \
    libxcb-xfixes0

RUN pip3 install ultralytics==8.3.0 --no-deps
RUN pip3 install numpy==1.26.4
RUN pip3 install tqdm

# Install glog, gflags
RUN apt-get update && apt-get install -y libgflags2.2 libgflags-dev libgoogle-glog-dev python3-requests

# Install xvfb to provide a display to container for GUI realted testing.
RUN apt-get update && apt-get install -y xvfb python3-dev python3-setuptools

RUN pip3 install setuptools pre-commit scipy matplotlib argcomplete

# install CSparse
RUN DEBIAN_FRONTEND=noninteractive apt install -y libsuitesparse-dev

# Parallelism C++ for CPU
RUN apt-get update && apt-get install -y libboost-all-dev libtbb-dev

WORKDIR /root/



# Install OpenCV for Ubuntu
RUN apt-get update && apt-get install -y \
      unzip \
      libjpeg-dev libpng-dev libpng++-dev libtiff-dev libgtk2.0-dev \
      libatlas-base-dev gfortran

RUN git clone https://github.com/opencv/opencv.git
RUN cd opencv && \
      git checkout tags/4.10.0 && \
      mkdir build

RUN git clone https://github.com/opencv/opencv_contrib.git
RUN cd opencv_contrib && \
      git checkout tags/4.10.0

RUN cd opencv/build && \
      cmake -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
      -D BUILD_opencv_python=OFF \
      -D BUILD_opencv_python2=OFF \
      -D BUILD_opencv_python3=ON \
      -D WITH_CUDA=ON \
      -D WITH_CUDNN=ON \
      -D INSTALL_CUDA_LIBS=OFF \
      -D CMAKE_CUDA_ARCHITECTURES="75" \
      -D OPENCV_DNN_CUDA=ON \
      -D ENABLE_FAST_MATH=ON \
      -D CUDA_FAST_MATH=ON \
      -D WITH_CUFFT=ON \
      -D WITH_CUBLAS=ON \
      -D WITH_TBB=ON \
      -DOPENCV_EXTRA_MODULES_PATH=/root/opencv_contrib/modules .. && \
      make -j$(nproc) install


RUN git clone https://github.com/MIT-SPARK/config_utilities.git
RUN cd config_utilities/config_utilities && mkdir build && \
      cd build && \
      cmake .. && make -j$(nproc) install



# Install GTSAM
RUN git clone https://github.com/borglab/gtsam.git
RUN cd gtsam && \
    git fetch && \
    git checkout tags/4.2.0 && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DGTSAM_USE_SYSTEM_EIGEN=ON \
    -DGTSAM_BUILD_TESTS=OFF -DGTSAM_BUILD_EXAMPLES_ALWAYS=OFF -DCMAKE_BUILD_TYPE=Release -DGTSAM_BUILD_UNSTABLE=ON -DGTSAM_POSE3_EXPMAP=ON -DGTSAM_ROT3_EXPMAP=ON -DGTSAM_TANGENT_PREINTEGRATION=OFF .. && \
    make -j$(nproc) install


# Install Open_GV
RUN git clone https://github.com/MIT-SPARK/opengv
RUN cd opengv && \
      mkdir build
RUN cd opengv/build && \
      cmake -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr/local \
      .. && make -j$(nproc) install


# Install Pangolin
RUN apt-get update && apt-get install -y build-essential cmake git pkg-config \
    libglew-dev libgl1-mesa-dev libx11-dev libjpeg-dev libpng-dev libepoxy-dev
RUN git clone https://github.com/stevenlovegrove/Pangolin.git
RUN cd Pangolin && \
      mkdir build && \
      cd build && \
      cmake .. && make -j$(nproc) install
RUN sed -i 's/attributes\.memoryType/attributes.type/g' /usr/local/include/pangolin/image/memcpy.h


# Install Sophus
RUN git clone https://github.com/strasdat/Sophus.git
RUN cd Sophus && \
      mkdir build && \
      cd build && \
      cmake .. && make -j$(nproc) install


# Install dynamic_slam_interfaces
RUN git clone https://github.com/ACFR-RPG/dynamic_slam_interfaces.git
RUN source /opt/ros/kilted/setup.bash && \
      cd dynamic_slam_interfaces && \
      mkdir build && \
      cd build && \
      cmake .. && make -j$(nproc) install


RUN unset OPENMPI_VERSION
RUN unset OMPI_MCA_coll_hcoll_enable
RUN unset OPAL_PREFIX
RUN export PATH=$(echo $PATH | tr ':' '\n' | grep -v '/opt/hpcx' | grep -v '/usr/local/mpi/bin' | paste -sd:)

RUN apt-get update && apt-get install -y libopenmpi-dev openmpi-bin

RUN mkdir -p /home/user/dev_ws/src/core \
    /home/user/dev_ws/src/third_parties \
    /home/user/upstream_ws/src

SHELL ["/bin/bash", "-c"]

RUN source /opt/ros/kilted/setup.bash

# Add aliases to .bashrc
RUN echo "" >> /root/.bashrc && \
    echo "# DynoSAM aliases" >> /root/.bashrc && \
    echo "alias dynobuild='cd /home/user/dev_ws && env -u OPAL_PREFIX -u HPCX_VERSION colcon build --packages-select dynosam --cmake-clean-cache --cmake-args -DPython3_EXECUTABLE=/usr/bin/python3 --event-handlers console_direct+ && source /home/user/dev_ws/install/setup.bash'" >> /root/.bashrc && \
    echo "alias runros='ros2 launch dynosam_ros dyno_sam_online_m3dgr.py v:=1'" >> /root/.bashrc && \
    echo "alias runtum='./install/dynosam/lib/dynosam/dyno_sam --use_tum   --path_to_tum=/root/data/tum-rgbd/fr_2_desk/   --tum_association=/root/data/tum-rgbd/fr2_desk/rgbd_dataset_freiburg2_large_with_loop_associated.txt   --use_pipeline=true   --output_trajectory=/root/results/trajectory_tum.txt   --use_dynamic_track=false    --v=1'" >> /root/.bashrc

WORKDIR /home/user/dev_ws
