FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Basic tools + ROS1 prerequisites
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl wget \
    git vim \
    python3-pip \
    locales tzdata \
    lsb-release gnupg2 dirmngr \
    && rm -rf /var/lib/apt/lists/*
RUN apt install -y build-essential

RUN locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

# ROS1 (Noetic)
RUN set -eux; \
    curl -fsSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | \
      gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg; \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" \
      > /etc/apt/sources.list.d/ros1-latest.list; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
      ros-noetic-desktop-full \
      python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool python3-catkin-tools; \
    rm -rf /var/lib/apt/lists/*

RUN rosdep init || true && rosdep update

RUN echo "source /opt/ros/noetic/setup.bash" >> /root/.bashrc

ENV ROS_DISTRO=noetic
ENV ROS_ROOT=/opt/ros/noetic/share/ros
ENV ROS_PACKAGE_PATH=/opt/ros/noetic/share
ENV PATH=/opt/ros/noetic/bin:$PATH
ENV LD_LIBRARY_PATH=/opt/ros/noetic/lib:$LD_LIBRARY_PATH
ENV PYTHONPATH=/opt/ros/noetic/lib/python3/dist-packages:$PYTHONPATH